In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
data = pandas.read_csv('traindata.txt', delimiter=',', header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,-0.26,0.43,-0.30,0.76,-0.14,-0.23,-0.28,-0.81,-0.10,0.58,...,-0.90,-0.32,0.10,1,2,7,5,5,1,1
1,-0.15,-0.24,-0.68,-0.27,0.69,0.45,-0.05,-0.58,-0.12,0.41,...,-0.49,1.05,-0.66,2,3,3,6,4,1,1
2,0.74,-1.09,-0.01,-0.49,-0.71,-0.41,0.28,-1.47,0.45,0.03,...,0.71,0.12,-0.36,2,2,1,1,5,1,0
3,-1.08,-0.43,0.83,0.98,-0.41,0.01,0.65,0.59,0.12,-0.52,...,0.51,0.70,0.44,0,3,1,5,3,0,0
4,0.18,0.96,0.01,0.33,0.63,-0.16,-0.24,-0.27,0.23,0.49,...,0.95,-1.22,0.38,0,6,7,6,5,1,-1

In [3]:
labels = pandas.read_csv('trainlabels.txt', delimiter=' ', header=None)
labels.head()

   0
0  6
1  2
2  6
3  1
4  9

In [4]:
X = data
y = labels
print(np.shape(y))
print(np.shape(X))

scaler = StandardScaler()
#scaler.fit(data)
#scaled_data=scaler.transform(data)
#
pca=PCA(n_components=25)
#pca.fit(scaled_data)
#x_pca=pca.transform(scaled_data)
#print(np.shape(scaled_data))
#print(np.shape(x_pca))

#plt.figure(figsize=(8,6))
#plt.scatter(x_pca[:,0],x_pca[:,1], c=y)
#plt.xlabel('First principle component')
#plt.ylabel('Second principle component')
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Create the MLP classifier
classifier = MLPClassifier(hidden_layer_sizes=(100, 100), max_iter=1000)

# Train the classifier
classifier.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = classifier.predict(X_test)

print("Predicted labels:", y_pred)

(10000, 1)
(10000, 71)

/usr/lib/python3/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1096: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Predicted labels: [1 4 7 ... 8 3 3]

In [5]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4465